### ISSUE TITLE
Cannot refer to Blocks in assertions around block presence

### ISSUE THREAD

**Issue by inkarkat** [MiniDigger/MiniTestFramework#3]
`helper.assertBlock[Not]Present()` and `helper.succeedWhenBlockPresent()` take a block argument, but won't accept any of the predefined static constants in `net.minecraft.world.level.block.Blocks`.

```javascript
const Blocks = Java.type('net.minecraft.world.level.block.Blocks');

registry.register("test3", (helper) => {
    console.log(Blocks);
    console.log(Blocks.GLASS);

    // The test structure is a simple button connected via Redstone to a piston that pushes a glass block.
    helper.pressButton(3, 2, 1);
    helper.assertBlockPresent(Blocks.GLASS, 1, 2, 0); // Note: Using an assert here because the succeedWhenBlockPresent() crashes the whole server.
});
```
```
[11:13:57 INFO]: class net.minecraft.world.level.block.Blocks
[11:13:57 INFO]: undefined
[11:13:57 ERROR]: test.test3 failed! Cannot invoke "net.minecraft.world.level.block.Block.g()" because "block" is null
```

Other static Java constants can be looked up this way:

```javascript
const JavaLocale = Java.type('java.util.Locale');

registry.register("test3", (helper) => {
    console.log(JavaLocale.GERMAN);
});
```    
```
[11:13:57 INFO]: de
```

### workaround

If I add a binding for `Blocks.GLASS` to `MiniTestFramework#createContext()`, it works as expected:

```java
import net.minecraft.world.level.block.Blocks;

public final class MiniTestFramework extends JavaPlugin {
    // [...]
    private Context createContext() {
        final Context context = Context.newBuilder("js")
        // [...]
        bindings.putMember("glass", Blocks.GLASS); // New binding for glass
        return context;
    }
}
```
```javascript
registry.register("test3", (helper) => {
    console.log(glass);
    helper.assertBlockPresent(glass, 1, 2, 0);
});
```
```
[11:13:57 INFO]: Block{minecraft:glass}
[11:13:57 ERROR]: test.test3 failed! Expected Glass, got Air at 348,70,80 (relative: 1,2,0) (t=0)
```

Just adding a registration for `Blocks` (which should be equivalent to the `Java#type()` lookup from above) doesn't work:

```java
// bindings.putMember("Blocks", Blocks.class);
```

Asserting that a particular block is present in the world is crucial test functionality. Having to modify the test framework code (especially in a not very maintainable way by enumerating all block types) should not be necessary.

**Comment by inkarkat** [comment]
Oh, and this is not just for Blocks, but also for the Rotation that needs to be passed to some of the `MiniTestFramework#register()` overloads.

```java
bindings.putMember("Rotation", Rotation.class);
```
```javascript
registry.register("defaultBatch", "test3", Rotation.NONE, 100, 0, false, 1, 2, (helper) => { ... }
```
causes an exception:

```
[16:08:03 ERROR]: 'test runthis' threw an exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.EnumBlockRotation.a(net.minecraft.world.level.block.EnumBlockRotation)"
because the return value of "net.minecraft.gametest.framework.GameTestHarnessTestFunction.g()" is null
        at net.minecraft.gametest.framework.GameTestInfo.<init>(GameTestInfo.java:56) ~[app:?]
```

As with the glass block, the enum value(s) need to be registered in the bindings:

```java
bindings.putMember("NoRotation", Rotation.NONE);
```
```javascript
registry.register("defaultBatch", "test3", NoRotation, 100, 0, false, 1, 2, (helper) => { ... }
```

**Comment by MiniDigger** [comment]
making this work is kinda meh because you are not running a mojmapped server, I dont think thats in scope right now, ill create an issue

**Comment by inkarkat** [comment]
Ah, so I'm supposed to run `gradlew runMojangMappedServer` instead of the [documented `gradlew runServer`](https://github.com/MiniDigger/MiniTestFramework/blob/master/README.md?plain=1#L37)?!

The server where I'm actually interested in running this also has the problem, so unless turning on Mojang-mapping is possible without negative effects (I'd have to consult with the team for this), I'm still interested in getting #4 addressed.

**Comment by MiniDigger** [comment]
mojang mapped means that the server isn't obfuscated, which might mean that some plugins refuse to work because they expect obfuscated packages.
the paper team will introduce ways to load these plugins on a mojmappd server in the future
